sudo: required
language: php
dist: trusty

php:
  - 7.1

install:
  - travis_retry composer install --no-interaction

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - cp .env.testing .env
  - php artisan serve &

script:
  - php artisan dusk

env:
  global:
    - secure: "qnxuin6Jde2TH9fYXvHT0k1yxKo/EMR8II4c7yJivYI3LjFD8hZS3L40Ig09u60K9j8kdpZ1xj7WlXN56y91jNUhxs0x0qcgnFTFRuhBR4SplK2kKgfzQn5mvGBK8NIy9xJo/XVOG1p3fBrwfmdQ/g3nsbXHWFZnliavsm3LvDRQxZZ5QfMifori1tdl2EWKbmmoEd6I6qBYUlDSXdKCxFW5t7iM8cf2Xm01l8vfxjWyIls+tQDD54CKEIVSBK5xNyuHO2JbkV7lsJm72SOSmTaG8SSvy3K5fEMlnxF4rx15+cHKQ6Nh0w31HsA23udAqCKonYfci3jdbh2J795EEU0ADnkpxFwzV4ytVM0ibwSLiShMmpYBgSAoPFydepYS4iGr5V3vqhKK3KOg1pU+aOvfdLo9irdVMq7N/yUu9Rpl0KB3et3kXIQPArTLO4qJX5nev3U1y1agVnznJlBKOnzzVD+yJax8hIvJAdJFhKA2NtqIJc4NTTu4vP18YpkpLJcjxniym239jydpef5LG2RNrIfuNVKgcfb5HyGPuQCpwkegm3Z72F4Nh2JHJq3ykipLVHW/nr8ZF8Z55GoCiAF0GsC/jbZQ6iUTHEkD05AyCTMPM9mVAX7s2h2jyYEm5VwUtP5PL/W77Babx6bMmD9txdBSlf6IhFt1bzAStP8="
    - secure: "qWBW1NU8RwK0sTkSOSkrPVRrXLuPhk+67jyKBsvoUOJOEqHivQZRJ+TWOKwkcCom9PNO1nau5MdvSZOZDXGWIoTKi5S685xepp5DoYS7O8DepMh1UULqcK7rPOv4VxUbcn/BbQERKrWDspR7mCvVNguOirTdnrR3Cyv/36bMprPpJWnBLdycBaKDhhyIWELLdhElb+ycGbHTLE/E2ycWgQpEkqQJUizno7zH7KaF0F3SV9x/s/9d6qpgc/fcqM7yyubaN863QLxV6qs03bjNkN8SedqeAyf4hkB+RIjUIyovlsEwrijZ1sb8E0dY8Uc/UrdlDeqvMCsP6i/W6GkQZatg4iMdqAEwo2aogrYvptFbKTMUOHE1aPyuaz1s4tpRJ/PbaZdYfTnl/roDzuScLjlWc0L6pK7CzJa+BhlhLE0AlKVOamXNAx25ovpwYQ9dS66zVr2qEgEhsVDEzLOphvJboHeyeMMIXm/DXHwKFqWmADc3vFlszf87yBXjKKH1GW8p7bONo59ghOx9cfscD1dQpHSc6u5x+5pI/p+ri8SRnX7CMUyFHMJrp9wyngbP+Waq7ZsUm7iYD2tHK6jnm104WRxNXwlK+5JULqxqzaUJhGjmfJ+Xg1bf0pYDpol1P7RbUBpAxhJ5XSNm4YBL3MAGiHWcOVHsd7OuGDahEPY="
